# @author Christian Checchetti
# The model defines the defect electrical behavior during the simulation.
# Four different models must be implemented according to IEEE-2427 standard:
#   - short_model
#   - open_model
#   - open_gate_model: used to test MOSFET gates
#   - parametric_model
# Models are defined as subckt in the AST generated by EDACurry

from abc import ABC, abstractmethod
from typing import Optional
import math
from .utility import DefectRecord, DefectType, Actions, Reverter

import sys
from pathlib import Path
edacurry_exec_path = Path(__file__).resolve().parent.parent.parent.parent/"build"
sys.path.append(str(edacurry_exec_path))
import edacurry



# Every model generates a defect record
class DefectModel(ABC):
    _defect_id: str                       # Defect record's attribute automatically generated and set externally
    _component_category: str              # Defect record's attribute
    _defect_instance : str                # defect record's attribute
    _name : str                           # model name (also a defect record attribute)
    _multiplier : Optional[int]           # defect record's attribute
    _weight : float                       # defect record's attribute
    _collapsed : Optional[int]            # defect record's attribute
    _merged : Optional[int]               # defect record's attribute
    _0_w_j : Optional[str]                # defect record's attribute

    _circuit: edacurry.Circuit


    def __init__(self, circuit, defect_id, component_category, defect_instance, name, multiplier, weight, collapsed, merged, z_w_j):
        try:
            self._circuit = circuit
            if self._circuit is None:
                raise ValueError("[DefectModel] Initialization error: Invalid circuit")
            self._defect_id = defect_id
            self._component_category = component_category
            self._defect_instance = defect_instance
            self._name = name
            self._multiplier = multiplier
            self._weight = weight
            self._collapsed = collapsed
            self._merged = merged
            if weight == 0 and z_w_j is None:
                raise ValueError(f"[DefectModel] Initialization error [{defect_id} @{defect_instance} - {name}]: The justification behind a zero-weighted defect must be provided.\n")
            self._z_w_j = z_w_j
        except (Exception) as e:
            print(f"[DefectModel] Initialization error [{defect_id} @{defect_instance} - {name}]: {e}\n")


    @abstractmethod
    def get_record(self) -> DefectRecord:
        pass

    @abstractmethod
    def generate_subckt(selfself) -> edacurry.Subckt:
        pass

    @abstractmethod
    def inject(self, reverter : Reverter) -> None:
        pass

    @abstractmethod
    def get_info(self) -> dict:
        pass

    def get_defected_circuit(self) -> edacurry.Circuit:
        return self._circuit




class OpenModel(DefectModel):
    _r_open : float = 1e9                 # default value is 1 GΩ
    _record: DefectRecord                 # Defect record associated to the model

    _n1 : str                             # Node 1
    _n2: str                              # Node 2


    def __init__(self, circuit, defect_id, component_category, defect_instance, name, multiplier, weight, collapsed, merged, z_w_j, n1, n2):
        try:
            super().__init__(circuit, defect_id, component_category, defect_instance, name, multiplier, weight, collapsed, merged, z_w_j)
            self._n1 = n1
            self._n2 = n2
            self._record = DefectRecord(defect_id, component_category, DefectType.OPEN, defect_instance, [n1, n2], name, multiplier, weight, collapsed, merged, z_w_j)
        except (Exception) as e:
            print(f"[OpenDefectModel] Initialization error [{defect_id} @{defect_instance} - {name}]: {e}\n")


    def get_record(self) -> DefectRecord:
        return self._record


    def generate_subckt(self) -> edacurry.Subckt:
        # Subckt generation via edacurry
        subckt = edacurry.Subckt(self._name);

        # Node definition
        n1 = edacurry.Node("n1")
        n2 = edacurry.Node("n2")
        subckt.nodes.append(n1)
        subckt.nodes.append(n2)

        # Ropen resistance definition
        r_open = edacurry.Component("R_open", "R")
        r_open.nodes.append(edacurry.Node("n1"))
        r_open.nodes.append(edacurry.Node("n2"))

        # Set resistance value as a parameter
        param = edacurry.Parameter(edacurry.Identifier("r"), edacurry.Double(self._r_open), edacurry.ParameterType.param_assign)
        r_open.parameters.append(param)

        # Add resistance to the subckt
        subckt.content.append(r_open)

        return subckt


    def inject(self, reverter : Reverter) -> None:

        instance_elements = self._defect_instance.split(".")

        # If the model is already present in the circuit, the AST is contaminated and the operation must be aborted
        component_name = instance_elements[-1]
        instance_elements.remove(component_name)
        om_subckt = edacurry.find_subckt(self._circuit, component_name)
        if om_subckt is not None:
            raise ValueError(f"[OpenDefectModel::inject] AST contamination detected @{self._defect_id}. Aborted\n")

        # Find subckt containing the component (if present)
        subckt_name = instance_elements[-1]
        target_subckt = None
        if subckt_name is not None:
            target_subckt = edacurry.find_subckt(self._circuit, subckt_name)

        # Find component (Can be found in the circuit or in a subckt)
        component = None
        if target_subckt is None:
            component = edacurry.find_component(self._circuit, component_name)
        else:
            component = edacurry.find_component(target_subckt, component_name)
        if component is None:
            raise ValueError(f"[OpenModel::inject] Unable to find component {component_name} in the AST @{self._defect_id}. Aborted\n")

        # The defect, realised as a subckt, must be injected between the nodes of the component, so n2 in the original component must be replaced by a new node
        new_node = f"{self._n2}_open"
        try:

            edacurry.rename_node(component, self._n2, new_node)
            operation = {
                "defect_type" : DefectType.OPEN,
                "action" : Actions.RENAME_NODE,
                "details" : {
                    "subckt" : subckt_name,
                    "component" : component_name,
                    "old_name" : self._n2,
                    "new_name" : new_node
                }
            }
            reverter.push(operation)

        except (Exception) as e:
            raise Exception(f"[OpenModel::inject] Unable to perform injection @{self._defect_id}: {e}. Aborted\n")

        # Generate and add subckt to the circuit AST
        try:
            om_subckt = self.generate_subckt()
        except Exception as e:
            raise Exception(f"[OpenDefectModel::inject] Unable to generate {self._name} subckt for defect {self._defect_id} : {e}\n")
        self._circuit.content.append(om_subckt)

        try:
            operation = {
                "defect_type" : DefectType.OPEN,
                "action" : Actions.ADD_SUBCKT,
                "details" : {
                    "subckt" : self._name,
                }
            }
            reverter.push(operation)
        except (Exception) as e:
            raise Exception(f"[OpenDefectModel::inject] Unable to perform injection @{self._defect_id}: {e}. Aborted\n")

        # Create phisical defect instance
        component_name = f"X{self._defect_id}"
        instance = edacurry.Component(component_name, self._name)

        # Connect instance to the proper nodes
        instance.nodes.append(edacurry.Node(new_node))
        instance.nodes.append(edacurry.Node(self._n2))

        # Insert instance in the correct scope
        target_scope = edacurry.find_subckt(self._circuit, subckt_name)
        if target_scope is None:
            raise Exception(f"[OpenDefectModel::inject] Unable to define the proper injection scope\n")

        # Append defect instance
        target_scope.content.append(instance)

        try:
            operation = {
                "defect_type" : DefectType.OPEN,
                "action" : Actions.ADD_INSTANCE,
                "details" : {
                    "subckt" : subckt_name,
                    "component" : component_name
                }
            }
            reverter.push(operation)
        except (Exception) as e:
            raise Exception(f"[OpenModel::inject] Unable to perform injection @{self._defect_id}: {e}. Aborted\n")

        print(f"\n[OpenModel::inject] Injection succeeded @{self._defect_id}\n")


    def get_info(self) -> dict:
        record_dict = self._record.get_info()
        info_dict = {
            "r" : self._r_open,
            "defect_record" : record_dict
        }
        return info_dict




class ShortModel(DefectModel):
    _r_short: float = 100.0                 # default value is 100 Ω
    _record: DefectRecord                   # Defect record associated to the model

    _n1 : str                               # Node 1
    _n2 : str                               # Node 2

    def __init__(self, circuit, defect_id, component_category, defect_instance, name, multiplier, weight, collapsed, merged, z_w_j, n1, n2):
        try:
            super().__init__(circuit, defect_id, component_category, defect_instance, "short_model", multiplier, weight, collapsed, merged, z_w_j)
            self._n1 = n1
            self._n2 = n2
            self._record = DefectRecord(defect_id, component_category, DefectType.SHORT, defect_instance, [n1, n2], name, multiplier, weight, collapsed, merged, z_w_j)
        except (Exception) as e:
            print(f"[ShortModel] Initialization error [{defect_id} @{defect_instance} - {name}]: {e}\n")

    def get_record(self) -> DefectRecord:
        return self._record

    def generate_subckt(self) -> edacurry.Subckt:
        # Subckt generation via edacurry
        subckt = edacurry.Subckt(self._name);

        # Node definition
        n1 = edacurry.Node("n1")
        n2 = edacurry.Node("n2")
        subckt.nodes.append(n1)
        subckt.nodes.append(n2)

        # Rshort resistance definition
        r_open = edacurry.Component("R_short", "R")
        r_open.nodes.append(edacurry.Node("n1"))
        r_open.nodes.append(edacurry.Node("n2"))

        # Set resistance value as a parameter
        param = edacurry.Parameter(edacurry.Identifier("r"), edacurry.Double(self._r_short), edacurry.ParameterType.param_assign)
        r_open.parameters.append(param)

        # Add resistance to the subckt
        subckt.content.append(r_open)

        return subckt

    def inject(self, reverter : Reverter) -> None:
        instance_elements = self._defect_instance.split(".")

        # If the model is already present in the circuit, the AST is contaminated and the operation must be aborted
        component_name = instance_elements[-1]
        instance_elements.remove(component_name)
        os_subckt = edacurry.find_subckt(self._circuit, component_name)
        if os_subckt is not None:
            raise ValueError(
                f"[ShortDefectModel::inject] AST contamination detected @{self._defect_id}. Aborted\n")

        # Find subckt containing the component (if present)
        subckt_name = instance_elements[-1]
        target_subckt = None
        if subckt_name is not None:
            target_subckt = edacurry.find_subckt(self._circuit, subckt_name)

        # Find component (Can be found in the circuit or in a subckt)
        component = None
        if target_subckt is None:
            component = edacurry.find_component(self._circuit, component_name)
        else:
            component = edacurry.find_component(target_subckt, component_name)
        if component is None:
            raise ValueError(
                f"[ShortDefectModel::inject] Unable to find component {component_name} in the AST @{self._defect_id}. Aborted\n")

        # Generate and add subckt to the circuit AST
        try:
            os_subckt = self.generate_subckt()
        except Exception as e:
            raise Exception(
                f"[ShortDefectModel::inject] Unable to generate {self._name} subckt for defect {self._defect_id} : {e}\n")
        self._circuit.content.append(os_subckt)

        try:
            operation = {
                "defect_type": DefectType.SHORT,
                "action": Actions.ADD_SUBCKT,
                "details": {
                    "subckt": self._name,
                }
            }
            reverter.push(operation)
        except Exception as e:
            raise Exception(f"[ShortDefect::inject] Unable to perform injection @{self._defect_id} : {e}. Aborted\n")

        # Create phisical defect instance
        component_name = f"X{self._defect_id}"
        instance = edacurry.Component(component_name, self._name)

        # Connect instance to the proper nodes
        instance.nodes.append(edacurry.Node(self._n1))
        instance.nodes.append(edacurry.Node(self._n2))

        # Insert instance in the correct scope
        target_scope = edacurry.find_subckt(self._circuit, subckt_name)
        if target_scope is None:
            raise Exception(f"[ShortDefectModel::inject] Unable to define the proper injection scope\n")

        # Append defect instance
        target_scope.content.append(instance)

        try:
            operation = {
                "defect_type": DefectType.SHORT,
                "action": Actions.ADD_INSTANCE,
                "details": {
                    "subckt": subckt_name,
                    "component": component_name
                }
            }
            reverter.push(operation)
        except Exception as e:
            raise Exception(f"[ShortDefect::inject] Unable to perform injection @{self._defect_id} : {e}. Aborted\n")

        print(f"\n[ShortModel::inject] Injection succeeded @{self._defect_id}\n")


    def get_info(self) -> dict:
        record_dict = self._record.get_info()
        info_dict = {
            "r": self._r_short,
            "defect_record": record_dict
        }
        return info_dict



class OpenGateModel(DefectModel):

    _record : DefectRecord
    _defect_id : str                        # Open gate model id

    # Nodes: A MOSFET transistor has four terminals: drain, gate, source and bulk
    _d_node : str                           # Drain
    _g_node : str                           # Gate
    _s_node : str                           # Source
    _g_new_node : str                       # New isolated gate

    # Resistances
    _r1 : float = 5e11                      # 500 GΩ resistance between Drain and internal node
    _r2 : float = 5e11                      # 500 GΩ resistance between Source and internal node
    _r3 : float = 1e12                      # 1TΩ resistance between internal node and Gate


    def __init__(self, circuit, defect_id, component_category, defect_instance, name, multiplier, weight, collapsed, merged, z_w_j, d_node, g_node, s_node, g_new_node):
        try:
            super().__init__(circuit, defect_id, component_category, defect_instance, "open_gate_model", multiplier, weight, collapsed, merged, z_w_j)
            self._defect_id = defect_id
            self._d_node = d_node
            self._g_node = g_node
            self._s_node = s_node
            self._g_new_node = g_new_node
            self._record = DefectRecord(defect_id, component_category, DefectType.OPEN, defect_instance, [d_node, g_node, s_node, g_new_node], name, multiplier, weight, collapsed, merged, z_w_j)
        except (Exception) as e:
            print(f"[OpenGateModel] Initialization error [{defect_id} @{defect_instance} - {name}]: {e}\n")


    def get_record(self) -> DefectRecord:
        return self._record


    def generate_subckt(self) -> edacurry.Subckt:
        # Subckt generation via edacurry
        subckt = edacurry.Subckt(self._name)

        # Node definition
        drain = edacurry.Node("d")
        gate = edacurry.Node("g")
        source = edacurry.Node("s")
        internal = edacurry.Node("n")
        subckt.nodes.append(drain)
        subckt.nodes.append(gate)
        subckt.nodes.append(source)

        # Resistances definition
        # Resistance between Drain and internal
        r_d_n = edacurry.Component("R_dn", "R")
        r_d_n.nodes.append(edacurry.Node("d"))
        r_d_n.nodes.append(edacurry.Node("n"))

        # Resistance between Source and internal
        r_s_n = edacurry.Component("R_sn", "R")
        r_s_n.nodes.append(edacurry.Node("s"))
        r_s_n.nodes.append(edacurry.Node("n"))

        # Resistance between Internal and Gate
        r_n_g = edacurry.Component("R_ng", "R")
        r_n_g.nodes.append(edacurry.Node("n"))
        r_n_g.nodes.append(edacurry.Node("g"))

        # Set resistances values as parameters
        # r_d_n
        param = edacurry.Parameter(edacurry.Identifier("r"), edacurry.Double(self._r1), edacurry.ParameterType.param_assign)
        r_d_n.parameters.append(param)

        # r_s_n
        param = edacurry.Parameter(edacurry.Identifier("r"), edacurry.Double(self._r2), edacurry.ParameterType.param_assign)
        r_s_n.parameters.append(param)

        # r_n_g
        param = edacurry.Parameter(edacurry.Identifier("r"), edacurry.Double(self._r3), edacurry.ParameterType.param_assign)
        r_n_g.parameters.append(param)

        # Add resistance to the subckt
        subckt.content.append(r_d_n)
        subckt.content.append(r_s_n)
        subckt.content.append(r_n_g)

        return subckt


    def get_info(self) -> dict:
        record_dict = self._record.get_info()
        info_dict = {
            "r1" : self._r1,
            "r2" : self._r2,
            "r3" : self._r3,
            "defect_record" : record_dict
        }
        return info_dict


    def inject(self, reverter : Reverter) -> None:
        # In this case, the injection consists in adding a new isolated gate that modifies MOSFET topology.
        # The component is modified in place without the need of adding new components
        instance_elements = self._defect_instance.split(".")

        # If the model is already present in the circuit, the AST is contaminated and the operation must be aborted
        component_name = instance_elements[-1]
        instance_elements.remove(component_name)
        og_subckt = edacurry.find_subckt(self._circuit, component_name)
        if og_subckt is not None:
            raise ValueError(
                f"[OpenGateModel::inject] AST contamination detected @{self._defect_id}. Aborted\n")

        # Find subckt containing the component (if present)
        subckt_name = instance_elements[-1]
        target_subckt = None
        if subckt_name is not None:
            target_subckt = edacurry.find_subckt(self._circuit, subckt_name)

        # Find component (Can be found in the circuit or in a subckt)
        component = None
        if target_subckt is None:
            component = edacurry.find_component(self._circuit, component_name)
        else:
            component = edacurry.find_component(target_subckt, component_name)
        if component is None:
            raise ValueError(f"[OpenGateModel::inject] Unable to find component {component_name} in the AST @{self._defect_id}. Aborted\n")

        # Retrieve the gate node
        gate_name = component.nodes[1].name
        if gate_name != self._g_node:
            raise ValueError(f"[OpenGateModel::inject] Mismatch between gate {gate.name} and {self._g_node} @{self._defect_id}. Aborted\n")

        # Gate disconnection
        edacurry.rename_node(component, self._g_node, self._g_new_node)
        try:
            operation = {
                "defect_type": DefectType.OPEN,
                "action": Actions.RENAME_NODE,
                "details": {
                    "subckt": subckt_name,
                    "component": component_name,
                    "old_name": self._g_node,
                    "new_name": self._g_new_node
                }
            }
            reverter.push(operation)
        except Exception as e:
            raise Exception(f"[OpenDefectModel::inject] Unable to perform injection @{self._defect_id} : {e}. Aborted\n")

        # Generate and add subckt to the circuit AST
        try:
            og_subckt = self.generate_subckt()
        except Exception as e:
            raise Exception(
                f"[OpenGateModel::inject] Unable to generate {self._name} subckt @{self._defect_id} : {e}\n")
        self._circuit.content.append(og_subckt)

        try:
            operation = {
                "defect_type": DefectType.OPEN,
                "action": Actions.ADD_SUBCKT,
                "details": {
                    "subckt": self._name,
                }
            }
            reverter.push(operation)
        except Exception as e:
            raise Exception(f"[OpenDefectModel::inject] Unable to perform injection @{self._defect_id} : {e}. Aborted\n")

        # Create phisical defect instance
        component_name = f"X{self._defect_id}"
        instance = edacurry.Component(component_name, self._name)

        # Connect instance to the proper nodes
        instance.nodes.append(edacurry.Node(self._d_node))
        instance.nodes.append(edacurry.Node(self._g_new_node))
        instance.nodes.append(edacurry.Node(self._s_node))

        # Insert instance in the correct scope
        parent_name = self._defect_instance.split(".")
        target_scope = edacurry.find_subckt(self._circuit, subckt_name)
        if target_scope is None:
            raise Exception(f"[OpenGateModel::inject] : Unable to define the proper injection scope @{self._defect_id}\n")

        # Append defect instance
        target_scope.content.append(instance)

        try:
            operation = {
                "defect_type": DefectType.OPEN,
                "action": Actions.ADD_INSTANCE,
                "details": {
                    "subckt": subckt_name,
                    "component": component_name
                }
            }
            reverter.push(operation)
        except Exception as e:
            raise Exception(f"[OpenDefectModel::inject] Unable to perform injection @{self._defect_id} : {e}. Aborted\n")

        print(f"\n[OpenGateModel::inject] Injection succeeded @{self._defect_id}\n")



class ParametricModel(DefectModel):
    # DefectModel _name parameter in a parametric defect must indicate the deviation direction, so it can only be MAX or MIN

    _parameter_name : str                   # "R" for resistances, "W" or "L" for MOSFETS
    _typical_value : float
    _pdk_corner_value : float
    _df_pdk : float = 2.0                   # 2.0 is the IEEE-2427 recommendation
    _defective_value : float                # Calculated according to IEEE 2427 Rule 3.2d/e
    _record : DefectRecord


    def __init__(self, circuit, defect_id, component_category, defect_instance, name, multiplier, weight, collapsed, merged, z_w_j, parameter_name, typical_value, pdk_corner_value):
        try:
            if name != "MIN" and name != "MAX":
                raise ValueError("Model name indicates the deviation direction, so it can only be 'MIN' or 'MAX'")
            super().__init__(circuit, defect_id, component_category, defect_instance, name, multiplier, weight, collapsed, merged, z_w_j)
            self._parameter_name = parameter_name
            self._typical_value = typical_value
            self._pdk_corner_value = pdk_corner_value

            # Calculate defective value
            deviation = abs(typical_value - pdk_corner_value)
            if name == "MAX":
                if typical_value >= 0:
                    self._defective_value = typical_value + (deviation * self._df_pdk)
                else:
                    self._defective_value = typical_value - (deviation * self._df_pdk)
            elif name == "MIN":
                val1 = None
                if typical_value >= 0:
                    val1 = typical_value - (deviation * self._df_pdk)
                else:
                    val1 = typical_value + (deviation * self._df_pdk)
                val2 = pdk_corner_value / self._df_pdk
                if typical_value >= 0:
                    self._defective_value = max(val1, val2)
                else:
                    self._defective_value = min(val1, val2)

            self._record = DefectRecord(self._defect_id, component_category, DefectType.OPEN, self._defect_instance, [], self._name, self._multiplier, self._weight, self._collapsed, self._merged, self._z_w_j)
        except (Exception) as e:
            print(f"[ParametricModel] Initialization error [{defect_id} @{defect_instance} - {name}]: {e}\n")


    def get_record(self) -> DefectRecord:
        return self._record


    def generate_subckt(self) -> None:
        return None


    def inject(self, reverter : Reverter) -> None:

        elements = self._defect_instance.split(".")

        component_name = elements[-1]
        elements.remove(component_name)

        subckt_name = None
        subckt = None
        if elements is not None:
            subckt_name = elements[-1]
            subckt = edacurry.find_subckt(self._circuit, subckt_name)

        # Find AST component and modify the parameter value in-place
        component = None
        if subckt is not None:
            component = edacurry.find_component(subckt, component_name)
        else:
            component = edacurry.find_component(self._circuit, component_name)
        if component is None:
            raise ValueError(f"[ParametricModel::inject] Component {component_name} not found in the AST @{self._defect_id}\n")

        target_param = edacurry.find_parameter(component, self._parameter_name)
        if target_param is None:
            raise ValueError(f"[ParametricModel::inject] Parameter {self._parameter_name} not found in the component {component_name} @{self._defect_id}\n")

        # Save original value for revert
        original_value = target_param.right

        # Modify the param by injecting the defective value
        target_param.right = edacurry.Double(self._defective_value)

        try:
            operation = {
                "defect_type" : DefectType.PARAMETRIC,
                "action" : Actions.CHANGE_PARAM,
                "details" : {
                    "subckt" : subckt_name,
                    "component" : component_name,
                    "parameter" : self._parameter_name,
                    "original_value" : original_value
                }
            }
            reverter.push(operation)
        except Exception as e:
            raise Exception(f"[ParametricModel::inject] Unable to perform injection @{self._defect_id} : {e}. Aborted\n")

        print(f"[ParametricModel::inject] Injection succeeded @{self._defect_id}\n")


    def get_info(self) -> dict:
        record_dict = self._record.get_info()
        info_dict = {
            "parameter_name" : self._parameter_name,
            "typical_value" : self._typical_value,
            "pdk_corner_value" : self._pdk_corner_value,
            "df_pdk" : self._df_pdk,
            "defective_value" : self._defective_value,
            "defect_record" : record_dict
        }
        return info_dict
