/// @file ngspice_backend.cpp
/// @author Christian Checchetti (chris22checchetti@gmail.com)
/// @copyright Copyright (c) 2021 sydelity.net (info@sydelity.com)
/// Distributed under the MIT License (MIT) (See accompanying LICENSE file or
///  copy at http://opensource.org/licenses/MIT)

#include "edacurry/backend/ngspice_backend.hpp"
#include "edacurry/classes.hpp"

#include <iostream>
#include <unordered_set>

namespace edacurry::backend {
NgspiceBackend::NgspiceBackend()
    : ss(4, ' ')
{
    // Nothing to do.
}


int NgspiceBackend::visitCircuit(const std::shared_ptr<structure::Circuit> &e)
{
    if (!e->getTitle().empty()) {
        ss << e->getTitle() << "\n";
    } else {
        ss << "* Empty title automatically generated by EDACurry\n"; // ngspice interprets the first row as the title,
                                                                     // so a title is needed to prevent parsing errors
    }

    if (e->nodes) {
        ss << ".global";
        for (const auto &node : e->nodes) {
            ss << ' ';
            node->accept(this);
        }
        ss << '\n';
    }

    if (e->parameters) {
        ss << ".param";
        for (const auto& parameter : e->parameters) {
            ss << ' ';
            parameter->accept(this);
        }
        ss << '\n';
    }

    for (const auto &it : e->content) {
        it->accept(this);
    }

    ss << ".end\n"; // closure directive needed by ngspice

    return 0;
}

int NgspiceBackend::visitAnalysis(const std::shared_ptr<structure::Analysis> &e)
{
    // The frontend names an analysis after the directive it came from, followed by
    // an underscore and the variant it matched: `ac_parameter_driven` came from
    // `.ac`, `dc_temperature_analysis` from `.dc`. So everything up to the first
    // underscore is the directive, and a name without one is the directive itself.
    // Listing the variants by hand covered `.ac` and `.tran` only, which silently
    // dropped the directive of the other thirty-three analyses and emitted a line
    // that no simulator can read.
    const std::string &name = e->getName();
    ss << '.' << name.substr(0, name.find('_'));
    for (const auto &parameter : e->parameters) {
        ss << ' ';
        parameter->accept(this);
    }
    ss << '\n';
    return 0;
}

int NgspiceBackend::visitComponent(const std::shared_ptr<structure::Component> &e) {
    //r2 1 2 res1
    ss << e->getName();
    if (e->nodes) {
        for (const auto &node : e->nodes) {
            ss << ' ';
            node->accept(this);
        }
    }

    if (!e->getMaster().empty())
        ss << ' ' << e->getMaster();

    if (e->parameters) {
        for (const auto &parameter : e->parameters) {
            ss << ' ';
            parameter->accept(this);
        }
    }
    ss << '\n';
    return 0;
}

int NgspiceBackend::visitControlScope(const std::shared_ptr<structure::ControlScope> &e) {
    // injection campaign is managed by Python at a higher level.
    // In future, if desired, it will be possible to add a .control ... .endc block to use alter, altermod and
    // alterparam interactively

    if (e->getControlType() == ctrl_altergroup) {
        std::string alter_directive = e->getName();
        std::string warning_message {"[NgspiceBackend::visitControlScope] Found incompatible .alter directive in the source file"};
        if (!alter_directive.empty()) {
            warning_message += ": .alter " + alter_directive;
        }
        warning_message += ". Ignored by visitor\n";
        warnings.push_back(warning_message);
        std::cerr << warning_message << std::endl;
    }

    return 0;
}

// Verify if an option is compatible with ngspice
bool is_eldo_only(const std::string &param) {

    static const std::unordered_set<std::string> eldo_only {
        "tuning", "ingold", "co", "keep_nodes", "a_art", "co_ratio", "post",
        "probe_all", "vntol_fast","lbound", "ubound", "tol", "tolerance", "weight"
    };

    return eldo_only.find(param) != eldo_only.end();
}

int NgspiceBackend::visitControl(const std::shared_ptr<structure::Control> &e) {

    std::string control;
    std::string warning_message;

    if (e->getControlType() == ctrl_option) {
        control = ".option";
    } else if (e->getControlType() == ctrl_save) {
        control = ".save";
    } else if (e->getControlType() == ctrl_print) {
        control = ".print";
    } else if (e->getControlType() == ctrl_plot) {
        control = ".plot";
    } else if (e->getControlType() == ctrl_probe) {
        const std::string &warning {"[NgspiceBackend::visitControl] Probe control is not supported by ngspice. "
                                        "Ignored by visitor\n"};
        warnings.push_back(warning);
        std::cerr << warning_message << std::endl;
        return 0; // probe is not supported
    } else if (e->getControlType() == ctrl_temp) {
        control = ".temp";
    } else if (e->getControlType() == ctrl_meas) {
        control = ".meas";
    }

    ss << control;

    if (!e->getName().empty())
        ss << " " << e->getName();
    for (const auto &parameter : e->parameters) {
        ss << ' ';
        parameter->accept(this);
    }
    ss << '\n';

    return 0;

}

int NgspiceBackend::visitExpressionUnary(const std::shared_ptr<structure::ExpressionUnary> &e)
{
    ss << operator_to_string(e->getOperator());
    if (e->getValue()) {
        e->getValue()->accept(this);
    }
    return 0;
}

int NgspiceBackend::visitExpression(const std::shared_ptr<structure::Expression> &e)
{
    if (e->getFirst()) {
        e->getFirst()->accept(this);
        ss << ' ';
    }
    ss << operator_to_string(e->getOperator());
    if (e->getSecond()) {
        ss << ' ';
        e->getSecond()->accept(this);
    }
    return 0;
}

int NgspiceBackend::visitFunctionCall(const std::shared_ptr<structure::FunctionCall> &e)
{
    ss << e->getName() << '(';
    if (e->parameters) {
        size_t size = e->parameters.size(), i = 0;
        for (const auto &parameter : e->parameters) {
            parameter->accept(this);
            if (i++ < (size - 1))
                ss << ", ";
        }
    }
    ss << ')';
    return 0;
}

int NgspiceBackend::visitIdentifier(const std::shared_ptr<structure::Identifier> &e)
{
    if (!e->getName().empty())
        ss << e->getName();
    return 0;
}

int NgspiceBackend::visitInclude(const std::shared_ptr<structure::Include> &e)
{
    return features::BaseVisitor::visitInclude(e);
}

int NgspiceBackend::visitLibraryDef(const std::shared_ptr<structure::LibraryDef> &e)
{
    return features::BaseVisitor::visitLibraryDef(e);
}

int NgspiceBackend::visitLibrary(const std::shared_ptr<structure::Library> &e)
{
    return features::BaseVisitor::visitLibrary(e);
}

int NgspiceBackend::visitModel(const std::shared_ptr<structure::Model> &e)
{
    // .MODEL pfet PMOS ( LEVEL = 8
    ss << ".MODEL " << e->getName() << " " << e->getMaster() << "(";
    for (const auto &parameter : e->parameters) {
        ss << ' ';
        parameter->accept(this);
    }
    ss << ")\n";
    return 0;
}

int NgspiceBackend::visitNode(const std::shared_ptr<structure::Node> &e)
{
    ss << e->getName();
    return 0;
}

int NgspiceBackend::visitUnsigned(const std::shared_ptr<structure::Number<unsigned>> &e)
{
    ss << e->getValue();
    if (!e->getUnit().empty())
        ss << e->getUnit();
    return 0;
}

int NgspiceBackend::visitInt(const std::shared_ptr<structure::Number<int>> &e)
{
    ss << e->getValue();
    if (!e->getUnit().empty())
        ss << e->getUnit();
    return 0;
}

int NgspiceBackend::visitDouble(const std::shared_ptr<structure::Number<double>> &e)
{
    ss << e->getValue();
    if (!e->getUnit().empty())
        ss << e->getUnit();
    return 0;
}

int NgspiceBackend::visitParameter(const std::shared_ptr<structure::Parameter> &e)
{
    if ((e->getType() == param_assign) || (e->getType() == param_arithmetic)) {
        if (e->getLeft() && !e->getHideName()) {
            auto ident = std::dynamic_pointer_cast<const structure::Identifier>(e->getLeft());
            if (ident) {
                std::string identifier = ident->getName();
                std::transform(std::begin(identifier), std::end(identifier), std::begin(identifier), ::tolower);

                if (is_eldo_only(identifier)) {
                    std::string warning_message;
                    warning_message.append("[NgspiceBackend::visitParameter] Parameter ").append(identifier)
                            .append(" is not supported by ngspice. Ignored by visitor\n");
                    warnings.push_back(warning_message);
                    std::cerr << warning_message << std::endl;
                    return 1;
                }
            }
            e->getLeft()->accept(this);
        }
        if (e->getRight()) {
            auto ident = std::dynamic_pointer_cast<const structure::Identifier>(e->getRight());
            if (ident) {
                std::string identifier = ident->getName();
                std::transform(std::begin(identifier), std::end(identifier), std::begin(identifier), ::tolower);
                if (is_eldo_only(identifier)) {
                    std::string warning_message;
                    warning_message.append("[NgspiceBackend::visitParameter] Parameter ").append(identifier)
                            .append(" is not supported by ngspice. Ignored by visitor\n");
                    warnings.push_back(warning_message);
                    std::cerr << warning_message << std::endl;
                    return 1;
                }
            }
            if (e->getLeft() && !e->getHideName())
                ss << '=';
            if (e->getType() == param_arithmetic)
                ss << '{';
            e->getRight()->accept(this);
            if (e->getType() == param_arithmetic)
                ss << '}';
        }
    } else if (e->getType() == param_tabular) {
        const std::string &warning_message {"[NgspiceBackend::visitParameter] Tabular parameter is not supported by ngspice. "
                                            "Ignored by visitor\n"};
        warnings.push_back(warning_message);
        std::cerr << warning_message << std::endl;
        return 1;
    } else if (e->getType() == param_list) {
        if (e->getLeft()) {
            auto ident = std::dynamic_pointer_cast<const structure::Identifier>(e->getLeft());
            if (ident) {
                std::string identifier = ident->getName();
                std::transform(std::begin(identifier), std::end(identifier), std::begin(identifier), ::tolower);
                if (is_eldo_only(identifier)) {
                    std::string warning_message;
                    warning_message.append("[NgspiceBackend::visitParameter] Parameter ").append(identifier)
                            .append(" is not supported by ngspice. Ignored by visitor\n");
                    warnings.push_back(warning_message);
                    std::cerr << warning_message << std::endl;
                    return 1;
                }
            }
            e->getLeft()->accept(this);
        }
        ss << "(";
        auto table = std::dynamic_pointer_cast<const structure::ValueList>(e->getRight());
        for (size_t i = 0; table && (i < table->values.size()); ++i) {
            table->values[i]->accept(this);
            if (i < (table->values.size() - 1))
                ss << ' ';
        }
        ss << ')';
    } else if (e->getType() == param_no_equal) {
        if (e->getLeft()) {
            auto ident = std::dynamic_pointer_cast<const structure::Identifier>(e->getLeft());
            if (ident) {
                std::string identifier = ident->getName();
                std::transform(std::begin(identifier), std::end(identifier), std::begin(identifier), ::tolower);
                if (is_eldo_only(identifier)) {
                    std::string warning_message;
                    warning_message.append("[NgspiceBackend::visitParameter] Parameter ").append(identifier)
                            .append(" is not supported by ngspice. Ignored by visitor\n");
                    warnings.push_back(warning_message);
                    std::cerr << warning_message << std::endl;
                    return 1;
                }
            }
            e->getLeft()->accept(this);
        }
        if (e->getRight()) {
            auto ident = std::dynamic_pointer_cast<const structure::Identifier>(e->getRight());
            if (ident) {
                std::string identifier = ident->getName();
                std::transform(std::begin(identifier), std::end(identifier), std::begin(identifier), ::tolower);
                if (is_eldo_only(identifier)) {
                    std::string warning_message;
                    warning_message.append("[NgspiceBackend::visitParameter] Parameter ").append(identifier)
                            .append(" is not supported by ngspice. Ignored by visitor\n");
                    warnings.push_back(warning_message);
                    std::cerr << warning_message << std::endl;
                    return 1;
                }
            }
            if (e->getLeft())
                ss << " ";
            e->getRight()->accept(this);
        }
    }
    return 0;
}

int NgspiceBackend::visitSubckt(const std::shared_ptr<structure::Subckt> &e)
{
    ss << ".subckt " << e->getName();
    for (const auto &node : e->nodes) {
        ss << ' ';
        node->accept(this);
    }
    // parameters must be declared on the same line of the subckt declaration
    if (e->parameters) {
        for (const auto &parameter : e->parameters) {
            ss << ' ';
            parameter->accept(this);
        }
    }
    ss << '\n';
    ss << ind_increase;
    for (const auto &entry : e->content) {
        entry->accept(this);
    }
    ss << ind_decrease;
    ss << ".ends " << e->getName() << '\n';
    return 0;
}

int NgspiceBackend::visitString(const std::shared_ptr<structure::String> &e)
{
    ss << e->getString();
    return 0;
}

int NgspiceBackend::visitValuePair(const std::shared_ptr<structure::ValuePair> &e)
{
    if (e->getFirst()) {
        e->getFirst()->accept(this);
    }
    ss << ',';
    if (e->getSecond()) {
        e->getSecond()->accept(this);
    }
    return 0;
}

int NgspiceBackend::visitValueList(const std::shared_ptr<structure::ValueList> &e)
{
    ss << delimiter_type_open_char(e->getDelimiterType());
    if (e->values) {
        size_t size = e->values.size(), i = 0;
        for (const auto &value : e->values) {
            value->accept(this);
            if (i++ < (size - 1))
                ss << ", ";
        }
    }
    ss << delimiter_type_close_char(e->getDelimiterType());
    return 0;
}

std::pair<std::string, std::vector<std::string>> write_ngspice(const std::shared_ptr<structure::Object> &object) {
    edacurry::backend::NgspiceBackend backend;
    object->accept(&backend);
    return {backend.str(), backend.getWarnings()};
}

} // namespace edacurry::backend
